# Generated by Django 5.1.2 on 2024-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=10)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
