# Generated by Django 5.1.2 on 2024-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshersAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypass',
            name='pass_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
